id: P000455
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 2021-12-16 15:40:50.135938
source_metadata:
  id: bdr:W00KG09980
  title: ཁང་དཀར་ཚུལ་ཁྲིམས་སྐལ་བཟང་གི་གསུང་རྩོམ་ཕྱོགས་བསྒྲིགས།
  author: ''
  volumes:
    472b8f383b4149b5ad4257194875b781:
      image_group_id: I1KG568
      title: Volume 1 of gsung rtsom/_tshul khrims skal bzang
      volume_number: 1
      total_pages: 914
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
