id: opecha:P000455
initial_creation_type: ocr
source_metadata:
  id: bdr:W00KG09980
  title: ཁང་དཀར་ཚུལ་ཁྲིམས་སྐལ་བཟང་གི་གསུང་རྩོམ་ཕྱོགས་བསྒྲིགས།
  volume:
    472b8f383b4149b5ad4257194875b781:
      image_group_id: I1KG568
      title: Volume 1 of gsung rtsom/_tshul khrims skal bzang
      volume_number: 1
      total_pages: 914
  author: ''
ebook_metadata:
  title: ཁང་དཀར་ཚུལ་ཁྲིམས་སྐལ་བཟང་གི་གསུང་རྩོམ་ཕྱོགས་བསྒྲིགས།
  author: ''
  sku: P000455
  cover: cover.jpg
  layers:
  - pagination
