id: IA4DEFFBF
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T11:26:27+00:00'
last_modified: '2022-06-10T05:53:15.040356+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W00KG09980
  title: ཁང་དཀར་ཚུལ་ཁྲིམས་སྐལ་བཟང་གི་གསུང་རྩོམ་ཕྱོགས་བསྒྲིགས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    '0117':
      image_group_id: I1KG568
      title: Volume 1 of gsung rtsom/_tshul khrims skal bzang
      total_pages: 914
      order: 1
      base_file: 0117.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
